dist: trusty
sudo: false
language: java
jdk:
  - openjdk8
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_error: always
    on_cancel: always
    urls:
      - 'https://webhook.atomist.com/atomist/travis/teams/T489LV5QF'
cache:
  directories:
    - "$HOME/.m2"
